# Generated by Django 3.1.7 on 2021-05-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='var_cat',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=70),
        ),
    ]
